spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: redis123
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

cart:
  ttl-hours: 24

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
