spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: ecommerce
    password: ecommerce123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # sql 로그
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    openfeign:
      circuitbreaker: # CB 설정 활성화
        enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG # sql 로그 LEVEL
    org.hibernate.orm.jdbc.bind: TRACE

resilience4j:
  circuitbreaker: # CB 설정
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10 # 최근 10번 요청 관찰
        failure-rate-threshold: 50 # 50% 이상 실패 시 Circuit OPEN
        wait-duration-in-open-state: 10s # 10초 동안 요청 차단 후 Half-OPEN
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
    instances:
      product-service:
        base-config: default

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,circuitbreakerevents,refresh
