spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: ecommerce
    password: ecommerce123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # sql 로그
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.isj.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.hibernate.SQL: DEBUG # sql 로그 LEVEL
    org.hibernate.orm.jdbc.bind: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
