CREATE DATABASE userdb;
CREATE DATABASE productdb;
CREATE DATABASE orderdb;
CREATE DATABASE paymentdb;

GRANT ALL PRIVILEGES ON DATABASE userdb TO ecommerce;
GRANT ALL PRIVILEGES ON DATABASE productdb TO ecommerce;
GRANT ALL PRIVILEGES ON DATABASE orderdb TO ecommerce;
GRANT ALL PRIVILEGES ON DATABASE paymentdb TO ecommerce;
